[features]
seeds = false
skip-lint = false

[programs.devnet]
todo_list_app = "<ADD YOUR ADDRESS HERE>"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "<UPDATE HERE>"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
